/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.dao.DepartmentDAO;
import controller.EmployeeControl;
import controller.dao.TimeKeeperDAO;
import java.util.Date;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Department;
import model.Timekeeper;

/**
 *
 * @author Asus
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    DefaultTableModel departmentDTM, timekeeperDTM;
    private int selectedIndex;

    public MainView() {
        initComponents();
        setSize(1200, 700);
        this.setLocationRelativeTo(null);
        departmentDTM = (DefaultTableModel) deptTable.getModel();
        EmployeeView employeeView = new EmployeeView();
        EmployeeControl controller = new EmployeeControl(employeeView);
        jTabbedPane1.add("Nhân viên", employeeView);
        timekeeperDTM = (DefaultTableModel) timeTB.getModel();
        showDepartment();
        showTimekeeper();

        this.setTitle("Trang chủ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        deptTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        deleteDepartmentBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        noText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addressText = new javax.swing.JTextField();
        addDepartmentBTN = new javax.swing.JButton();
        editDepartmentBTN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        timeTB = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        addTimeBTN = new javax.swing.JButton();
        editTimeBTN = new javax.swing.JButton();
        deleteTimeBTN = new javax.swing.JButton();
        idTimeText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        inoutText = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        empidText = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        deptTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "NO", "Location"
            }
        ));
        jScrollPane2.setViewportView(deptTable);

        jLabel1.setText("    THÔNG TIN CÁC PHÒNG BAN");

        deleteDepartmentBTN.setText("Xóa");
        deleteDepartmentBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDepartmentBTNActionPerformed(evt);
            }
        });

        jLabel2.setText("THÊM PHÒNG BAN");

        jLabel3.setText("ID:");

        jLabel4.setText("Tên:");

        jLabel5.setText("NO:");

        jLabel6.setText("Địa chỉ:");

        addDepartmentBTN.setText("Thêm");
        addDepartmentBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDepartmentBTNActionPerformed(evt);
            }
        });

        editDepartmentBTN.setText("Sửa");
        editDepartmentBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDepartmentBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(247, 247, 247))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(addDepartmentBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(editDepartmentBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteDepartmentBTN)
                .addGap(314, 314, 314))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noText, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                .addGap(343, 343, 343))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addComponent(jLabel5))
                            .addComponent(noText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteDepartmentBTN)
                    .addComponent(editDepartmentBTN)
                    .addComponent(addDepartmentBTN))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Phòng Ban", jPanel1);

        timeTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TimeID", "DateTime", "In_Out", "EMP_ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(timeTB);

        jLabel12.setText("THÊM THÔNG TIN");

        jLabel13.setText("THÔNG TIN ĐI LÀM/NGHỈ PHÉP");

        addTimeBTN.setText("Thêm");
        addTimeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTimeBTNActionPerformed(evt);
            }
        });

        editTimeBTN.setText("Sửa");
        editTimeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTimeBTNActionPerformed(evt);
            }
        });

        deleteTimeBTN.setText("Xóa");
        deleteTimeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTimeBTNActionPerformed(evt);
            }
        });

        jLabel14.setText("ID :");

        jLabel16.setText("In_Out :");

        jLabel17.setText("EMP_ID");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(112, Short.MAX_VALUE)
                        .addComponent(addTimeBTN)
                        .addGap(79, 79, 79)
                        .addComponent(editTimeBTN))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(empidText)
                            .addComponent(inoutText)
                            .addComponent(idTimeText, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel13)
                        .addGap(296, 296, 296))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(deleteTimeBTN)
                                .addGap(309, 309, 309))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(empidText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(47, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(idTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(inoutText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(206, 206, 206)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(31, 31, 31)))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteTimeBTN)
                    .addComponent(editTimeBTN)
                    .addComponent(addTimeBTN))
                .addGap(47, 47, 47))
        );

        jTabbedPane1.addTab("Thông tin", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteTimeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTimeBTNActionPerformed
        // TODO add your handling code here:
        int removeIndex = timeTB.getSelectedRow();
        if (removeIndex == -1) {
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn một dòng rồi xóa !");
        } else {
            TimeKeeperDAO timeKeeperDAO = new TimeKeeperDAO();
            List<Timekeeper> timekeeperList = timeKeeperDAO.selectAllTimekeepers();
            Timekeeper selectedTimekeeper = timekeeperList.get(removeIndex);
            try {
                timeKeeperDAO.deleteTimeKeeper(selectedTimekeeper.getTimeID());
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            showTimekeeper();
        }
    }//GEN-LAST:event_deleteTimeBTNActionPerformed

    private void editTimeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTimeBTNActionPerformed
        // TODO add your handling code here:
        selectedIndex = timeTB.getSelectedRow();
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn một dòng cần sửa !");
        } else {
            EditTimeKeeper edit = new EditTimeKeeper(this, rootPaneCheckingEnabled);
            TimeKeeperDAO timeKeeperDAO = new TimeKeeperDAO();
            List<Timekeeper> timekeeperList = timeKeeperDAO.selectAllTimekeepers();
            edit.setEditData(timekeeperList.get(selectedIndex));
            edit.setVisible(true);
        }
    }//GEN-LAST:event_editTimeBTNActionPerformed

    private void addTimeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTimeBTNActionPerformed

        String ID = idTimeText.getText();
        String inout = inoutText.getText();
        long empID = Long.parseLong(empidText.getText());
        Timekeeper timekeeper = new Timekeeper(ID, new Date(System.currentTimeMillis()), inout, empID);
        TimeKeeperDAO timeKeeperDAO = new TimeKeeperDAO();
        try {
            timeKeeperDAO.insertTimekeeper(timekeeper);
        } catch (Exception e) {
            e.printStackTrace();
        }
        showTimekeeper();
    }//GEN-LAST:event_addTimeBTNActionPerformed

    private void editDepartmentBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDepartmentBTNActionPerformed
        selectedIndex = deptTable.getSelectedRow();
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn một dòng cần sửa !");
        } else {
            EditDepartment edit = new EditDepartment(this, rootPaneCheckingEnabled);
            DepartmentDAO departmentDAO = new DepartmentDAO();
            List<Department> departmentList = departmentDAO.selectAllDepartments();
            edit.setEditData(departmentList.get(selectedIndex));
            edit.setVisible(true);
        }
    }//GEN-LAST:event_editDepartmentBTNActionPerformed

    private void addDepartmentBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDepartmentBTNActionPerformed
        int id = Integer.parseInt(idText.getText());
        String name = nameText.getText();
        String no = noText.getText();
        String location = addressText.getText();
        Department department = new Department(id, name, no, location);
        DepartmentDAO departmentDAO = new DepartmentDAO();
        try {
            departmentDAO.insertDepartment(department);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        departmentDTM.addRow(department.toObjects());
    }//GEN-LAST:event_addDepartmentBTNActionPerformed

    private void deleteDepartmentBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDepartmentBTNActionPerformed
        int removeIndex = deptTable.getSelectedRow();
        if (removeIndex == -1) {
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn một dòng rồi xóa !");
        } else {
            DepartmentDAO departmentDAO = new DepartmentDAO();
            List<Department> departmentList = departmentDAO.selectAllDepartments();
            Department selectedDept = departmentList.get(removeIndex);
            try {
                departmentDAO.deleteDepartment(selectedDept.getDeptId());
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            departmentDTM.setRowCount(0);
            showDepartment();
        }
    }//GEN-LAST:event_deleteDepartmentBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDepartmentBTN;
    private javax.swing.JButton addTimeBTN;
    private javax.swing.JTextField addressText;
    private javax.swing.JButton deleteDepartmentBTN;
    private javax.swing.JButton deleteTimeBTN;
    private javax.swing.JTable deptTable;
    private javax.swing.JButton editDepartmentBTN;
    private javax.swing.JButton editTimeBTN;
    private javax.swing.JTextField empidText;
    private javax.swing.JTextField idText;
    private javax.swing.JTextField idTimeText;
    private javax.swing.JTextField inoutText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField noText;
    private javax.swing.JTable timeTB;
    // End of variables declaration//GEN-END:variables

    private void showDepartment() {
        DepartmentDAO departmentDAO = new DepartmentDAO();
        List<Department> departmentList = departmentDAO.selectAllDepartments();
        for (Department department : departmentList) {
            departmentDTM.addRow(department.toObjects());
        }
    }

    private void showTimekeeper() {
        timekeeperDTM.setRowCount(0);
        TimeKeeperDAO timeDAO = new TimeKeeperDAO();
        List<Timekeeper> timeList = timeDAO.selectAllTimekeepers();
        for (Timekeeper timeKeeper : timeList) {
            timekeeperDTM.addRow(timeKeeper.toObjects());
        }
    }

    public void update(Department department) {
        departmentDTM.setRowCount(0);
        showDepartment();
    }

    public void updateTimeKeeper(Timekeeper timekeeper) {
        timekeeperDTM.setRowCount(0);
        showTimekeeper();
    }

    void update(Timekeeper timekeeper) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
